Feature/report play head time
bitmovin/bitmovin-player-android-analytics-conviva pull request #54
Opened 2024-03-22 08:56 UTC by remyderuiter1

A new value that is needed in Conviva to get a pass on validation is the playhead time. This can be useful for example in error reporting, to know in what second the user has an issue. 

The following changes were made:

- Add new `TimeChanged` callback for reporting Playhead to conviva playback metric. Calculates Live and Vod playback for reporting.
- Updated conviva-core to 4.0.35

Build has been validated by Conviva:
NLZIET Android 5.0 -  App Version 5.7.5: https://pulse.conviva.com/app/appmanager/apps/5389/28241 - #20. Playhead Time (PHT) Passed (https://touchstone-conviva.conviva.com/ui?client=209004308.1313293974.1027138199.1109187838&pub=0&before=1710772679.4021997&session=876273758)
NLZIET Android TV 5.0  App Version 5.7.5: https://pulse.conviva.com/app/appmanager/apps/5392/28242 - 1. Playhead Time (PHT): Pass (https://touchstone-conviva.conviva.com/ui?client=836067775.1698472106.1392489906.2042532197&session=1096631015&pub=0&before=1710771018.5019999)
NLZIET FireTV 5.0 - App Version 5.7.5: Playhead Time (PHT) for VOD : PASSED

Some tests for `./gradlew ConvivaTestApp:connectedAndroidTest` seem to fail. I included the report.
<img width="597" alt="image" src="https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/assets/127963037/d112b17a-cc73-4b83-a7e8-d7e5bd46dc7c">
[androidTests.zip](https://github.com/bitmovin/bitmovin-player-android-analytics-conviva/files/14719223/androidTests.zip)

2024-03-22 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitmovin/bitmovin-player-android-analytics-conviva?pullRequest=54) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitmovin/bitmovin-player-android-analytics-conviva?pullRequest=54) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitmovin/bitmovin-player-android-analytics-conviva?pullRequest=54) it.</sub>

2024-03-25 16:01 UTC, dweinber requested changes
Thank you for your contribution!

Two remarks, I think we're good to go after that.

2024-03-26 09:14 UTC, remyderuiter1 commented on conviva/src/main/java/com/bitmovin/analytics/conviva/ConvivaAnalyticsIntegration.java
> +import static com.conviva.sdk.ConvivaSdkConstants.PLAYBACK.PLAY_HEAD_TIME;
I have removed the import and added the `ConvivaSdkConstants.PLAYBACK` reference.

2024-03-26 09:16 UTC, remyderuiter1 commented on conviva/src/main/java/com/bitmovin/analytics/conviva/ConvivaAnalyticsIntegration.java
> +        bitmovinPlayer.on(PlayerEvent.TimeChanged.class, onTimeChangedListener);
Good remark, I added the `bitmovinPlayer.off` now for the `onTimeChangedListener `.

2024-03-26 09:28 UTC, dweinber approved these changes
Thank you for your contribution!

2024-03-26 09:29 UTC, merged